config/routes.rb
Rails.application.routes.draw do
  # khi truy cập vào /admin thì gọi controller admin và def mặc định là index
  get 'admin' => 'admin#index'  
  resources :jobs
end

app/controllers/admin_controller.rb
# class AdminController sẽ kế thừa class ApplicationController
class AdminController < ApplicationController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
Hello from controller admin, def index

app/views/jobs/index.html.erb
This view will show list jobs.

app/views/layouts/_navigation.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dev Jobs", admin_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Jobs", jobs_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Login", "#" %>
        </li>
        <li>
          <%= link_to "Register", "#" %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>  
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>